# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_comments'),
        ('profiles', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='image',
            field=models.ManyToManyField(to='images.Image'),
        ),
        migrations.AddField(
            model_name='like',
            name='owner',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
