# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='../static/img', verbose_name='Image', width_field='width_field')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='all_categories', to='categories.Category')),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='all_comments', to='comments.Comment')),
            ],
        ),
    ]
