# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=src.images.models.content_file_name, verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_id', to='albums.Album')),
            ],
        ),
    ]
