# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import src.images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('comments', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=src.images.models.content_file_name, verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='all_comments', to='comments.Comment')),
                ('likes', models.ManyToManyField(blank=True, related_name='all_likes', to='likes.Like')),
                ('tags', models.ManyToManyField(blank=True, related_name='all_tags', to='tags.Tag')),
            ],
        ),
    ]
