# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_likes', to='likes.Like'),
        ),
    ]
