# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20170929_2151'),
        ('images', '0002_auto_20170924_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album_id', to='albums.Album'),
            preserve_default=False,
        ),
    ]
