# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import src.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20171003_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.images.models.content_file_name, verbose_name='Image'),
        ),
    ]
