# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
