# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20171012_2301'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.Image'),
        ),
    ]
