# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20170924_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='images',
            new_name='image',
        ),
    ]
