# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20170924_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
