# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170924_1937'),
        ('tags', '0005_auto_20170924_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='images',
        ),
        migrations.AddField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.Image'),
        ),
    ]
