# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
        ('comments', '0002_comment_image'),
        ('albums', '0002_album_images'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='../static/img', verbose_name='Profile picture', width_field='width_field')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('albums', models.ManyToManyField(blank=True, null=True, to='albums.Album')),
                ('commented', models.ManyToManyField(blank=True, null=True, to='comments.Comment')),
                ('images', models.ManyToManyField(blank=True, null=True, to='images.Image')),
                ('liked', models.ManyToManyField(blank=True, null=True, to='likes.Like')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
