# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170921_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='../static/img', verbose_name='Profile picture'),
        ),
    ]
