# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(related_name='album_images', to='images.Image'),
        ),
    ]
