# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
