# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
