# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_comments'),
        ('comments', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
